import oracledb
import os
import re

class OracleVectorManager:
    def __init__(self):
        self.dataset_md = []
        self.conn = oracledb.connect(
            user="SYS",
            password="YourSecurePassword123",
            dsn="localhost:1521/FREEPDB1",
            mode=oracledb.AUTH_MODE_SYSDBA
        )
        self.model_name = "ALL_MINILM_L12_V2" 
        self.initialize_db()

    def initialize_db(self):
        with self.conn.cursor() as cursor:
            try:
                cursor.execute(f"""
                    BEGIN
                        EXECUTE IMMEDIATE 'DROP TABLE EMBEDDINGS PURGE';

                        EXECUTE IMMEDIATE 'CREATE TABLE EMBEDDINGS (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            text_content VARCHAR2(4000),
                            vec VECTOR
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                """)
                print("Table ready.")
            except oracledb.Error as e:
                print(f"Setup error: {e}")

    def parse_md(self, folder_path):
        chunks = []
        for root, _, files in os.walk(folder_path):
            for filename in files:
                if not filename.endswith(".md"):
                    continue
                
                filepath = os.path.join(root, filename)
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()
                    title_match = re.search(r'title:\s*(.+)', content)
                    page_title = title_match.group(1).strip() if title_match else filename.replace('.md', '').replace('_', ' ')
                    
                    clean_content = re.sub(r'^---\n.*?\n---\n', '', content, flags=re.DOTALL).strip()
                    sections = re.split(r'\n(?=#+\s)', '\n' + clean_content)
                    
                    for section in sections:
                        section = section.strip()
                        if not section: continue
                        
                        first_line = section.split('\n')[0]
                        section_name = re.sub(r'^#+\s*', '', first_line).strip() if re.match(r'^#+', section) else "Overview"
                        
                        chunk_text = f"DOCUMENTATION FOR: {page_title} > {section_name}\n\n{section}"
                        if len(chunk_text) > 50:
                            chunks.append(chunk_text)
        return chunks

    def load_and_sync_db(self, folder_path):
        self.dataset_md = self.parse_md(folder_path)
        if not self.dataset_md:
            print("No data found.")
            return

        added_count = 0
        with self.conn.cursor() as cursor:
            insert_sql = f"""
                INSERT INTO EMBEDDINGS (text_content, vec) 
                VALUES (:1, vector_embedding({self.model_name} USING :2 AS data))
            """
            for chunk in self.dataset_md:
                try:
                    cursor.execute(insert_sql, [chunk, chunk])
                    added_count += 1
                except oracledb.Error as e:
                    print(f"Insertion error: {e}")

            self.conn.commit()
        print(f'Successfully vectorized and stored {added_count} chunks.')

    def search(self, query_text, limit=5):
        search_sql = f"""
            SELECT text_content, 
                   vector_distance(vec, vector_embedding({self.model_name} USING :query AS data)) as distance
            FROM EMBEDDINGS
            ORDER BY distance
            FETCH FIRST :limit ROWS ONLY
        """
        
        results = []
        try:
            with self.conn.cursor() as cursor:
                cursor.execute(search_sql, query=query_text, limit=limit)
                for row in cursor:
                    results.append({"content": row[0], "score": row[1]})
            return results
        except oracledb.Error as e:
            print(f"Search error: {e}")
            return []

if __name__ == "__main__":
    manager = OracleVectorManager()
    manager.load_and_sync_db('./docs/mutators/')

    query = "How to configure a custom mutator?"
    results = manager.search(query)

    print(f"\n--- Search Results for: '{query}' ---")
    for i, res in enumerate(results, 1):
        print(f"{i}. {res['content']}")