import oracledb
import array
import ollama
import os
import re

class OracleVectorManager:
    def __init__(self):
        self.EMBEDDING_MODEL = 'embeddinggemma'
        self.dataset_md = []
        self.conn = self._connect_db()
        self.initialize_db()

    def _connect_db(self):
        return oracledb.connect(
            user="SYS",
            password="YourSecurePassword123",
            dsn="localhost:1521/FREEPDB1",
            mode=oracledb.AUTH_MODE_SYSDBA
        )

    def initialize_db(self):
        """ Creates the table if it doesn't exist """
        with self.conn.cursor() as cursor:
            try:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE TABLE EMBEDDINGS (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            text_content CLOB,
                            vec VECTOR
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                """)
                print("Database table ready.")
            except oracledb.Error as e:
                print(f"Setup error: {e}")

    def parse_md(self, folder_path):
            """  Split the MD file into chunks """
            chunks = []

            for root, _, files in os.walk(folder_path):
                for filename in files:
                    if not filename.endswith(".md"):
                        continue
                    
                    filepath = os.path.join(root, filename)
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()

                        title_match = re.search(r'title:\s*(.+)', content)
                        page_title = title_match.group(1).strip() if title_match else filename.replace('.md', '').replace('_', ' ')
                        
                        clean_content = re.sub(r'^---\n.*?\n---\n', '', content, flags=re.DOTALL).strip()
                        
                        sections = re.split(r'\n(?=#+\s)', '\n' + clean_content)
                        
                        for section in sections:
                            section = section.strip()
                            if not section:
                                continue
                            
                            section_name = "Overview"
                            # FIX 2: Dynamically extract the name regardless of header level
                            if re.match(r'^#+', section):
                                first_line = section.split('\n')[0]
                                section_name = re.sub(r'^#+\s*', '', first_line).strip()
                            
                            chunk_text = f"DOCUMENTATION FOR: {page_title} > {section_name}\n\n{section}"
                            
                            # FIX 3: Ignore chunks that are too small to have meaning (under 50 chars)
                            if len(chunk_text) > 50:
                                chunks.append(chunk_text)

            return chunks

    def load_dataset(self):
        self.dataset_md = self.parse_md('./docs/')
        print(f'Loaded {len(self.dataset_md)} Markdown entries.')

    def add_chunks_to_db(self):
        if not self.dataset_md:
            print("No data loaded.")
            return

        added_count = 0
        with self.conn.cursor() as cursor:
            for chunk in self.dataset_md:
                # Get embedding from Ollama
                response = ollama.embed(model=self.EMBEDDING_MODEL, input=chunk)
                embedding = response['embeddings'][0]
                
                # Oracle expects a float array ('f' for 32-bit float)
                vector_data = array.array("f", embedding)
                
                try:
                    cursor.execute(
                        "INSERT INTO EMBEDDINGS (text_content, vec) VALUES (:1, :2)",
                        [chunk, vector_data]
                    )
                    added_count += 1
                except oracledb.Error as e:
                    print(f"Error inserting chunk: {e}")

            self.conn.commit()
        print(f'Successfully added {added_count} chunks to Oracle AI Vector Search.')

# Execution
manager = OracleVectorManager()
manager.load_dataset()
manager.add_chunks_to_db()